definitions:
  authentication.RegisterUser:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  authentication.ResponsAuthorization:
    properties:
      message:
        type: string
    type: object
  authentication.ResponseErrorBadRequest:
    properties:
      ErrorField:
        items:
          additionalProperties:
            type: string
          type: object
        type: array
    type: object
  authentication.ResponseErrorInternalServer:
    properties:
      error:
        type: string
    type: object
  authentication.ResponseSuccess:
    properties:
      success:
        type: string
    type: object
  authentication.Verification:
    properties:
      code:
        type: integer
    type: object
  dto.Category:
    properties:
      category:
        maxLength: 100
        type: string
      createdAt:
        type: string
      id:
        type: integer
      updatedAt:
        type: string
    required:
    - category
    type: object
  products.CategoryInput:
    properties:
      category:
        type: string
    type: object
  products.ProductInput:
    properties:
      categoryId:
        type: integer
      hargaProduct:
        type: number
      image:
        type: string
      namaProduct:
        type: string
      type:
        type: string
    type: object
  products.ResponseErrorBadRequest:
    properties:
      errorFields:
        items:
          additionalProperties:
            type: string
          type: object
        type: array
    type: object
  products.ResponseErrorInternalServer:
    properties:
      error:
        type: string
    type: object
  products.ResponseErrorNotFound:
    properties:
      message:
        type: string
    type: object
  products.ResponseProduct:
    properties:
      categoryGender:
        type: string
      categoryId:
        type: integer
      created_at:
        type: string
      hargaProduct:
        type: number
      id:
        type: integer
      image:
        type: string
      namaProduct:
        type: string
      type:
        type: string
      updated_at:
        type: string
    type: object
  products.ResponseSuccess:
    properties:
      Success:
        type: string
    type: object
info:
  contact: {}
paths:
  /category:
    get:
      description: Get detailed information of all data category and product based
        on category
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved list of categories with details
          schema:
            items:
              $ref: '#/definitions/dto.Category'
            type: array
        "404":
          description: No categories found
          schema:
            $ref: '#/definitions/products.ResponseErrorNotFound'
        "500":
          description: Internal server error while processing the request
          schema:
            $ref: '#/definitions/products.ResponseErrorInternalServer'
      summary: Get All Data Category
      tags:
      - Category
  /category/input:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Add a new category to the system
      parameters:
      - description: Category Input
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/products.CategoryInput'
      produces:
      - application/json
      responses:
        "200":
          description: Category successfully added to the system
          schema:
            $ref: '#/definitions/products.ResponseSuccess'
        "400":
          description: Invalid request or incomplete category data
          schema:
            $ref: '#/definitions/products.ResponseErrorBadRequest'
        "500":
          description: Internal server error while processing the request
          schema:
            $ref: '#/definitions/products.ResponseErrorInternalServer'
      summary: post data Category
      tags:
      - Category
  /login/user:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: This enpoint is used to authenticate users with send cridential
        data (email dan password).
      parameters:
      - description: Login Input
        in: body
        name: Login
        required: true
        schema:
          $ref: '#/definitions/authentication.RegisterUser'
      produces:
      - application/json
      responses:
        "200":
          description: Successfuly login, return a token to access enpoint for user
          schema:
            $ref: '#/definitions/authentication.ResponseSuccess'
        "400":
          description: Request invalid or the data sent is incorrect
          schema:
            $ref: '#/definitions/authentication.ResponseErrorBadRequest'
        "500":
          description: Mistake in the server
          schema:
            $ref: '#/definitions/authentication.ResponseErrorInternalServer'
      summary: User Login
      tags:
      - authentication
  /product:
    get:
      description: This endpoint is used to retrieve a list of all products along
        with detailed information for each product. It also allows you to get the
        details of a specific product by its ID. The response will include information
        like product name, description, price, and other relevant details.
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved list of products and their details
          schema:
            items:
              $ref: '#/definitions/products.ResponseProduct'
            type: array
        "404":
          description: Products not found
          schema:
            $ref: '#/definitions/products.ResponseErrorNotFound'
        "500":
          description: Internal server error while processing the request
          schema:
            $ref: '#/definitions/products.ResponseErrorInternalServer'
      summary: Retrieve All Product Data
      tags:
      - Product
    post:
      consumes:
      - multipart/form-data
      description: Add a new Product to the system
      parameters:
      - description: Product Input
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/products.ProductInput'
      produces:
      - application/json
      responses:
        "200":
          description: Product successfully added to the system
          schema:
            $ref: '#/definitions/products.ResponseSuccess'
        "400":
          description: Invalid request or incomplete product data
          schema:
            $ref: '#/definitions/products.ResponseErrorBadRequest'
        "500":
          description: Internal server error while processing the request
          schema:
            $ref: '#/definitions/products.ResponseErrorInternalServer'
      summary: post data Product
      tags:
      - Product
  /product/female:
    get:
      description: Get detailed information of all data Product Female
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved list of female products with details
          schema:
            items:
              $ref: '#/definitions/products.ResponseProduct'
            type: array
        "404":
          description: No female products found
          schema:
            $ref: '#/definitions/products.ResponseErrorNotFound'
        "500":
          description: Internal server error while processing the request
          schema:
            $ref: '#/definitions/products.ResponseErrorInternalServer'
      summary: Get All Data Product Female
      tags:
      - Product
  /product/male:
    get:
      description: Get detailed information of all data Product Male
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved list of male products with details
          schema:
            items:
              $ref: '#/definitions/products.ResponseProduct'
            type: array
        "404":
          description: No male products found
          schema:
            $ref: '#/definitions/products.ResponseErrorNotFound'
        "500":
          description: Internal server error while processing the request
          schema:
            $ref: '#/definitions/products.ResponseErrorInternalServer'
      summary: Get All Data Product Male
      tags:
      - Product
  /signup/user:
    post:
      consumes:
      - application/json
      description: This endpoint is used to create a new user account by submitting
        registration data in JSON format. Users are required to provide information
        email, and password. The data will be validated on the server side before
        the account is created temporary, client have navigate to endpoint signup
        verification on the client side.
      parameters:
      - description: User Registration Data (name, email, password)
        in: body
        name: Signup
        required: true
        schema:
          $ref: '#/definitions/authentication.RegisterUser'
      produces:
      - application/json
      responses:
        "200":
          description: Account successfully created temporery, return a token to verification
            email
          schema:
            $ref: '#/definitions/authentication.ResponseSuccess'
        "400":
          description: Invalid request or incomplete data
          schema:
            $ref: '#/definitions/authentication.ResponseErrorBadRequest'
        "500":
          description: Internal server error while processing the request
          schema:
            $ref: '#/definitions/authentication.ResponseErrorInternalServer'
      summary: Create New User Account
      tags:
      - authentication
  /signup/verification:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: This endpoint is used to verify the user's email during the registration
        process. A verification code is sent to the user's email, and the user must
        input this code to complete the signup process successfully. The request must
        include the verification code in the form body.
      parameters:
      - description: Email Verification Data (code)
        in: body
        name: Signup
        required: true
        schema:
          $ref: '#/definitions/authentication.Verification'
      produces:
      - application/json
      responses:
        "200":
          description: Email successfully verified, account registration completed
          schema:
            $ref: '#/definitions/authentication.ResponseSuccess'
        "400":
          description: Invalid or missing verification code
          schema:
            $ref: '#/definitions/authentication.ResponseErrorBadRequest'
        "401":
          description: Unauthorized - Missing or invalid token
          schema:
            $ref: '#/definitions/authentication.ResponsAuthorization'
        "500":
          description: Internal server error while processing the request
          schema:
            $ref: '#/definitions/authentication.ResponseErrorInternalServer'
      summary: Verify User Email for Signup
      tags:
      - authentication
swagger: "2.0"
